### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waltare68** [arnabm14/Dev_AIChatbot_NLP#1]
Traceback (most recent call last):
  File "C:/Users/ROBOWALT/Music/Video/DevBot/dev.py", line 67, in <module>
    nlp = transformers.pipeline("conversational", model="microsoft/DialoGPT-medium")
  File "C:\Users\ROBOWALT\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\pipelines\__init__.py", line 454, in pipeline
    framework, model = infer_framework_load_model(
  File "C:\Users\ROBOWALT\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\pipelines\base.py", line 101, in infer_framework_load_model
    raise RuntimeError(
RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. To install TensorFlow 2.0, read the instructions at https://www.tensorflow.org/install/ To install PyTorch, read the instructions at https://pytorch.org/.

**Comment by arnabm14** [comment]
Try installing Tensorflow with "pip install Tensorflow" or use pip3 if you are using Python3. Let me know if it works.

**Comment by arnabm14** [comment]
Closing the issue After no response from the user after almost 2 months. This has solved the issue for other people who reached out to me on LinkedIn and feel free to open another issue there.

LinkedIn Link: https://www.linkedin.com/in/arnab1408/
